# .github/workflows/main.yml

name: Deploy Next.js App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      # 'next build'를 위해 .env.local 파일 생성 (이 단계는 여전히 필요)
      - name: Create .env file for build
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      # 배포 패키지 압축 (.env.local은 이제 포함하지 않음)
      - name: Create deployment package
        run: tar -czf deploy.tar.gz .next node_modules package.json

      - name: Transfer package to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.tar.gz"
          target: "/home/azureuser"

      # [가장 큰 변경점] SSH 실행 시 환경 변수를 직접 주입
      - name: Deploy application on Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # env 키를 통해 GitHub Secrets를 원격 셸의 환경 변수로 전달합니다.
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          script: |
            mkdir -p /home/azureuser/app
            mv /home/azureuser/deploy.tar.gz /home/azureuser/app/
            cd /home/azureuser/app
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            
            pm2 stop todo-app || true
            pm2 delete todo-app || true

            # ssh-action에 의해 주입된 환경 변수를 그대로 물려받아 앱이 실행됩니다.
            pm2 start "npx next start" --name "todo-app"

            pm2 save
            echo "🚀 Deployment successful!"